name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    CI:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/Checkout@v5
        - uses: actions/setup-python@v6
          with:
            python-version: '3.11'
        
        -name: Install Dependencies
        working-directory: 02-encontros-tech
          run: |
            python -m pip install --upgrade pip
            pip Install -r requirements.txt

        -name: Testes
          working-directory: 02-encontros-tech
          run: python -m pytest tests/ -v

        - run: echo "Executar o Docker Build"
        - run: echo "Enviar a imagem Docker para o Docker Hub"
    
    CD:
      runs-on: ubuntu-latest
      needs: [CI]
      steps:
        - run: echo "Obter CÃ³digo"
        - run: echo "Configurar o Kubeconfig"
        - run: echo "Executar o apply"
