name: CI-CD
# Gatilho da minha action. Ou seja, quando ela executa.
on:
  push:
    branches: ["main"]
  # Informo que posso executar minha pipe de forma manual
  workflow_dispatch:

# Aqui eu crio os meus jobs da pipeline CI e CD
jobs:
    CI:
      # Onde minha pipe vai rodar. (Se vai ser windows, linux e etc)
      runs-on: ubuntu-latest
      # passos a serem executados do meu job.
      steps:
        - name: Checkout
          uses: actions/Checkout@v5
          
        - uses: actions/setup-python@v6
          with:
            python-version: '3.11'
        
        - name: Install Dependencies
          working-directory: 02-encontros-tech
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Testes
          working-directory: 02-encontros-tech
          run: python -m pytest tests/ -v

        - run: echo "Executar o Docker Build"
        - run: echo "Enviar a imagem Docker para o Docker Hub"
    
    CD:
      # Onde minha pipe vai rodar. (Se vai ser windows, linux e etc)
      runs-on: ubuntu-latest
      # Informo que para rodar esta etapa eu preciso de ter concluído com sucesso o passo anterior
      needs: [CI]
       # passos a serem executados do meu job.
      steps:
        - run: echo "Obter Código"
        - run: echo "Configurar o Kubeconfig"
        - run: echo "Executar o apply"
